news/urls.py
from django.contrib import admin
from django.urls import include, re_path

urlpatterns = [
    re_path(r'^', include('posts.urls', namespace='posts')),
    re_path(r'admin/', admin.site.urls),
]

posts/urls.py
from django.urls import re_path
from . import views
import permission; permission.autodiscover()



app_name = "posts"

urlpatterns = [
        re_path(r'^$', views.home, name="home"),
        re_path(r'^staff/articles/$', views.all, name="all"),
        re_path(r'^staff/articles/new/$', views.new, name="new"),
        re_path(r'^staff/articles/(?P<id>\d+)/$', views.toggle_publish, name="toggle_publish"),
        re_path(r'^refresh/$', views.refresh, name="refresh"),
        re_path(r'^mail/$', views.mail, name="mail"),
        re_path(r'^number/$', views.numbers, name="number"),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime

from django.utils.dateformat import format

# Create your models here.

class News(models.Model):
    author = models.ForeignKey(User, unique=False, on_delete=models.CASCADE)
    audience = models.EnumField(default=1)
    disabled = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=True)
    # published = models.BooleanField(default=False, blank=True)
    # updated = models.DateTimeField(auto_now=True, auto_now_add=False) for auto-updating func/button


class NewsContent(models.Model):
    news = models.ForeignKey(News, unique = True, on_delete=models.CASCADE)
    title = models.CharField (max_length=200)
    content = models.CharField (max_length=30000)
    image = models.CharField (max_length=200)
    locale = models.EnumField (default=1)
    timestamp = models.DateTimeField (auto_now=True, auto_now_add=True)

class NewsLanuage(models.Model):
    locale = models.EnumField(default=1)

    class Meta:
        ordering = ['-timestamp', '-updated']

    def __str__(self):
        return self.title

    def unix_time(self):
        return format(self.updated, 'U')

    

class LastUpdate(models.Model):
    updated = models.DateTimeField(auto_now=False, auto_now_add=True)

    def unix_time(self):
        return format(self.updated, 'U')

    def __str__(self):
        return self.unix_time()

posts/forms.py
from django import forms
from .models import Post
import datetime

YEAR_CHOICES = tuple([2000+i for i in range(22)])

class PostForm(forms.ModelForm):

    title = forms.CharField(
        required=True, 
        label = "Write a title...",
        widget=forms.TextInput(
            attrs={
            'class':'form-control',
            'id':'id_title',
            'placeholder': "article title",
            'label':''
            }))


    timestamp = forms.DateField(
        label='Select Publish Date',
        initial = datetime.datetime.now(),
        widget=forms.SelectDateWidget(
            attrs={
                'class':'form-control',
                },
            years=YEAR_CHOICES)
    )

    content = forms.CharField(
        label="Write a content...",
        widget=forms.Textarea(
            attrs={
                'class':'form-control',
                'id':'id_content',
                'rows':10,
                'placeholder': "article body",
                'label':''
                }))

    class Meta:
        model = Post
        fields = [
        'title',
        'content',
        'timestamp',
        ]

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from .models import Post, LastUpdate
import time, datetime
from .forms import PostForm
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.core import mail
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from news.tasks import email_admin
# Create your views here.

@cache_page(None)
def home(request):
    """
    This is the public view that displays only published posts. 
    The view also returns a UNIX timestamp of the most recently updated post.
    This timestamp is compared with the `LastUpdate` value to determine when the page should be refreshed.
    Every 5 seconds, the `latest` timestamp is compared with the `LastUpdate` timestamp. 
    If `LastUpdate` is greater that `latest`, this implies that a Post has either been published or unpublished.
    """

    posts = Post.objects.filter(published=True)
    latest = 0
    if posts:
        latest = Post.objects.latest('updated').unix_time()

    return render(request, 'posts/home.html', {'posts':posts, 'latest':latest})

@login_required
def all(request):
    """
    This is a view for staff members that shows all posts, published or unpublished
    Each Post has a link that displays the Post and presents the option to publish or unpublish the post
    """

    posts = Post.objects.filter()

    print("made a query")
    return render(request, 'posts/all.html', {'posts':posts})

@login_required
def toggle_publish(request,id):
    """
    This view allows an authenticated staff user to publish or unpublish an article by clicking a button.
    Clicking the button toggles the current state of the selected Post's `published` field.
    It also updates the `LastUpdated` time to be the time when the Post was updated (saved), tracked by its `updated` field
    This field uses `auto_now=True`, which updates the datetime field to the time at which the record is saved.
    Finally, the button triggers the clearing of the cache.
    This removes the cached home page and forces it to be refreshed with the published (or unpublished post).
    """
    
    instance = get_object_or_404(Post, id=id)

    if request.method=="POST":
        instance.published = not instance.published
        instance.save()

        t, created = LastUpdate.objects.get_or_create(id=1)

        t.updated = instance.updated
        t.save()

        cache.clear()
        return redirect('posts:home')

    context = {'post':instance}

    return render(request, 'posts/publish.html', context)

@login_required
def new(request):
    """
    This form allows for a staff user to create a new post.
    It does not publish the post, but it redirects to a page where the post can be reviewed and published.
    """

    form = PostForm(request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            return HttpResponseRedirect(reverse('posts:toggle_publish', args=(instance.id,)))

    context = {'form':form}

    return render(request, 'posts/new.html', context)

def refresh(request):
    """
    This is the URL that is polled by the public-facing page.
    It returns a UNIX timestamp of the last time an article was published or unpublished. 
    This timestamp comes from the `LastUpdated`, a table that stores and updates only one row with one datetime column.
    Publishing and unpublishing are the only two actions that clear the cached homepage. 
    When the returned UNIX timestamp is greater than the UNIX timestamp of the most recently updated article,
    The page is refreshed with `location.reload()`.
    """
    
    t, created = LastUpdate.objects.get_or_create(id=1)
    if created:
        t.save()
        t = t.unix_time()
    else:
        t = t.unix_time()
    latest = int(t) - 2
    return JsonResponse({'latest':int(latest)})


def mail(request):
    """
    A test function for sending mail.
    """
    email_admin.delay('testinggg')
    return JsonResponse({"details":"working"})

posts/templates/posts/all.html
{% extends 'base.html' %}
{% block title %}Staff | {{ block.super}}{% endblock %}

{% block content %}

<div class="container">
{% include 'nav.html' %}
{% for post in posts %}

<div class="card">
    <div class="card-block">
        <h4 class="card-title">{{ post.title | safe }}</h4>
        <h6 class="card-subtitle mb-2 text-muted"><small>by {{ post.user.username }} on {{ post.timestamp | date}}</small></h6>
        <hr >
        <p class="card-text">{{ post.content | safe | linebreaks }}</p>
        <a href="{% url 'posts:toggle_publish' id=post.id %}" class="card-link">Manage Post</a>
    </div>
</div>

{% endfor %}
</div>
{% endblock %}

posts/templates/posts/home.html
{% extends 'base.html' %}
{% block title %}Home | {{ block.super}}{% endblock %}
{% block content %}

<div class="container">

    {% include 'nav.html' %}
    <div display="none" data="{{ latest }}" id="last"></div>
    {% for post in posts %}
    <div class="card">
        <div class="container">
        <div class="card-block">
            <h4 class="card-title">{{ post.title | safe }}</h4>
            <h6 class="card-subtitle mb-2 text-muted"><small>by {{ post.user.username }} on {{ post.timestamp | date}}</small></h6>
            <hr>
            <p class="card-text">{{ post.content | safe | linebreaks }}</p>
        </div>
    </div>
    </div>
    {% endfor %}

</div>

<script>
    console.log("working")
    poll = function() {
        $.ajax({
        url: '/refresh',
        dataType: 'json',
        type: 'get',
        success: function(data) {
            var latest = parseInt(data.latest)
            var latest_local = parseInt($("#last").attr('data'))
            console.log("latest", latest);
            console.log("latest_local", latest_local);

            if (latest > latest_local + 2){
                location.reload()
            }
            
        },
        error: function() {
            console.log('The refresh poll was not successful');
        }
        });
    },
    pollInterval = setInterval(function() {
        poll();
        }, 5000);

</script>
{% endblock %}

posts/templates/posts/new.html
{% extends 'base.html' %}

{% block title %}Staff | {{ block.super}}{% endblock %}
{% block content %}

<div class="container">
    {% include 'nav.html' %}
    <h6>Write your Django News article here:</h6>
    <form action="{% url 'posts:new' %}" method="POST">
        {% csrf_token %}
        {{ form.title }}
        {{ form.content }}
        {{ form.timestamp.label }}
        <div class="row" >
            <div class="container">
                {{ form.timestamp }}
            </div>
        </div>
        <input type="submit" id="id_submit" class="btn btn-success" value="Finish" />
    </form>
</div>

{% endblock %}

posts/templates/posts/publish.html
{% extends 'base.html' %}

{% block title %}Staff | {{ block.super}}{% endblock %}
{% block content %}

<div class="container">
    {% include 'nav.html' %}
    <div class="row">
        
        <div class="container">
        <form action="{% url 'posts:toggle_publish' id=post.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" id="toggle-publish" class="btn btn-success pull-right" value="{% if post.published %}Unpublish{% else %}Publish{% endif %}" />
        </form>
    </div>
    </div>
    <p>publish settings</p>

    <br />
    <div class="card">
        <div class="container">
            <div class="card-block">
                <h4 class="card-title">{{ post.title}}</h4>
                <h6 class="card-subtitle mb-2 text-muted"><small>by {{ post.user.username }} on {{ post.timestamp | date}}</small></h6>
                <hr>
                <p class="card-text">{{ post.content }}</p>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>{% block title %}Django News{% endblock %}</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>    <!-- Bootstrap CSS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/nav.html
<nav class="navbar navbar-custom navbar-expand-sm bg-light">

            <a class="navbar-brand" href="{% url 'posts:home' %}">Django News</a>
              <!-- Links -->
              <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'posts:all' %}">Staff Portal</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="new-article" href="{% url 'posts:new' %}">New Article</a>
                </li>
                {% endif %}
                <li class="nav-item pull-right">
                    <a class="nav-link pull-right" href="{% url 'posts:mail' %}">Email Admin</a>
                  </li>
              </ul>

            
            </nav>